In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# 데이터 로드
url = "https://raw.githubusercontent.com/MyungKyuYi/AI-class/main/heart.csv"
df = pd.read_csv(url)
df

In [2]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [3]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [4]:
df['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [5]:
# 데이터와 타겟 분리
X = df.drop('target', axis=1).values
y = df['target'].values     

In [6]:
# 테스트를 위한 feature, 테스트를 위한 정답 값
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [7]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [15]:
# 모델 정의 및 훈련 (SVM)
svm_model = SVC()
svm_model.fit(X_train, y_train)

# 예측
svm_y_pred = svm_model.predict(X_test)

# 정확도 평가
svm_accuracy = accuracy_score(y_test, svm_y_pred)
print(f"SVM Accuracy: {svm_accuracy:.4f}")
print(confusion_matrix(y_test, svm_y_pred)) 

SVM Accuracy: 0.6885
[[13 14]
 [ 5 29]]


In [17]:
# 모델 정의 및 훈련 (Logistic Regression)
lr_model = LogisticRegression(max_iter=1000, solver='liblinear')
lr_model.fit(X_train, y_train)

# 예측
lr_y_pred = lr_model.predict(X_test)

# 정확도 평가
lr_accuracy = accuracy_score(y_test, lr_y_pred)
print(f"Logistic Regression Accuracy: {lr_accuracy:.4f}")
print (confusion_matrix(y_test, lr_y_pred))

Logistic Regression Accuracy: 0.8525
[[22  5]
 [ 4 30]]


In [25]:
from sklearn.neighbors import KNeighborsClassifier

# 모델 정의 및 훈련 (KNN)
knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)

# 예측
knn_y_pred = knn_model.predict(X_test)

# 정확도 평가
knn_accuracy = accuracy_score(y_test, knn_y_pred)
print(f"KNN Accuracy: {knn_accuracy:.4f}")
print (confusion_matrix(y_test, knn_y_pred))

KNN Accuracy: 0.6393
[[17 10]
 [12 22]]


In [27]:
# 모델 정의 및 훈련 (Decision Tree)
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

# 예측
dt_y_pred = dt_model.predict(X_test)

# 정확도 평가
dt_accuracy = accuracy_score(y_test, dt_y_pred)
print(f"Decision Tree Accuracy: {dt_accuracy:.4f}")
print (confusion_matrix(y_test, dt_y_pred))

Decision Tree Accuracy: 0.7869
[[22  5]
 [ 8 26]]


In [31]:
from sklearn.ensemble import RandomForestClassifier

# 모델 정의 및 훈련 (Random Forest)
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)

# 예측
rf_y_pred = rf_model.predict(X_test)

# 정확도 평가
rf_accuracy = accuracy_score(y_test, rf_y_pred)
print(f"Random Forest Accuracy: {rf_accuracy:.4f}")
print (confusion_matrix(y_test, rf_y_pred))

Random Forest Accuracy: 0.9016
[[23  4]
 [ 2 32]]
